#! /usr/bin/env ruby

require 'pg'
require 'yaml'

def help
  commands = YAML.load(File.read('./commands.yml'))
  puts "An expense recording system\n\nCommands:\n\n"

  length = commands.keys.max { |a, b| a.length <=> b.length }.length

  commands.each do |command, desc|
    puts "#{command.ljust(length)} : #{desc}"
  end
end


def list_expenses(db)
  expenses = db.exec('SELECT * FROM expenses')

  expenses.each do |tuple|
    id = tuple['id'].rjust(3)
    amount = tuple['amount'].rjust(12)
    date = tuple['created_on'].rjust(10)
    memo = tuple['memo']

    puts "#{id} | #{date} | #{amount} | #{memo}"
  end
end

database = PG.connect(dbname: "expense_tracker")

help

list_expenses(database)


